config/routes.rb
AllSeats::Application.routes.draw do

  get "/collections/:id" => "collections#show", as: :collection

  mount Rich::Engine => '/rich', :as => 'rich'

  get "search/events" => 'search#index', as: :filter
  get "search/free_search" =>'search#show', as: :free_search
  get "search/autocomplete", :to => 'search#autocomplete', :as => :autocomplete

  get "/performer/events" => 'performers#events', as: :performer_tickets

  get "/venue/events" => 'venues#events', as: :venue_tickets

  get 'static/:permalink', :controller => 'static_pages', :action => 'show', :as => :static_page

  resources :performers, :only => [:show]
  resources :events, :only => [:show]
  resources :venues, :only => [:show]
  resources :locations, :only => [:show, :index]
  resources :contact_us_messages, :only => [:create]

  get "home/home"
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to=>'home#home'

  get "/:id" => "categories#show", as: :category
  get "/:category_id/:id" => "performers#show", as: :long_performer
  get "/:category_id/:performer_id/:date" => "events#show", as: :long_event

  post '/contact_us_messages/new'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :html, :json

  def show
  	require 'ticketnetwork'

  	#get data from server
  	@search_term = params[:search_term]
    begin
      response = Ticketnetwork.make_request(:search_events, {'searchTerms' => @search_term})
    rescue => e
      logger.error e
    end

    if response.nil?
      @events = []
    else
    #get events from db
  	event_tnids = Ticketnetwork.get_tnids response
  	params[:order_by] = 'date ASC' if !params[:order_by]
  	@events = Event.future.active
      .joins("LEFT OUTER JOIN venues ON venues.id = events.venue_id")
        .joins("LEFT OUTER JOIN locations ON events.location_id = locations.id")
          .order(params[:order_by]).where(:events => {:tnid => event_tnids })
            .page(params[:page]).per(20)
    end
  end

  def index

  	@events = Event.future.active
  	@events = @events.joins("LEFT OUTER JOIN venues ON venues.id = events.venue_id")
      .joins("LEFT OUTER JOIN locations ON locations.id = events.location_id")
    if params[:main_category] && params[:main_category] != "All Events"
  		@events = @events.where( "events.main_category = ?", params[:main_category])
  	end
    if params[:state] && params[:state] != "All States"
        @events = @events.where state_province: params[:state]
    end
  	if params[:name] && params[:name] != ""
  		@events = @events.where("upper(events.name) LIKE upper( ? ) OR upper(venues.name) LIKE upper( ? )",
  		  "%#{params[:name]}%",
  		  "%#{params[:name]}%")
  	end
  	if params[:date] && params[:date] != ""
	  	begin
	  		@events = @events.date(params[:date])
	  	rescue ArgumentError
		end
  	end
  	params[:order_by] = 'priority DESC' unless params[:order_by] && params[:order_by] != ""
  	@events = @events.order(params[:order_by])
  	@events = @events.page(params[:page]).per(20)
    render "index_page"
  end

  def autocomplete
    term = params[:term].downcase unless params[:term].nil?

    @performers = Performer.order(:name).where("lower(name) like ?", "%#{term}%").limit(5)
    @performers.collect!{ |performer| { :label => performer.name, :url => collectible_link(performer), :type => 'performer'} }

    @categories = Category.visible.order(:name).where("lower(name) like ?", "%#{term}%").limit(5)
    @categories.collect!{ |category| { :label => category.name, :url => collectible_link(category), :type => 'category'} }

    @results = @categories + @performers
#    @results = [{:label => "No results found", :url => "#", :type => 'none'}] if @results.empty?

    respond_to do |format|
      format.json { render :json => @results }
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper

  
end

app/views/search/index.html.erb
  <div class="container">
    <div class="row">
      <section class="span3">
        <%= render 'widgets/filter' %>
      </section>
      <section class="span9">
        <!-- Breadcrumbs -->
        <div id="breadcrumbs" class="row">
          <section class="span12"> <%= link_to "Home", root_path %> <span>Search Results</span> </section>
        </div>
        <!-- /Breadcrumbs -->
        <% if @events.length > 0 %>
        <section class="search-results">
          <section class="sort-by">
            <%= form_tag filter_path, method: 'get', id:"sort-field" do %>
            <p>
              <%= label_tag :order_by, "Sort by" %>
              <%= select_tag :order_by, options_for_select([
                ["","priority DESC"],
                ["Date - Ascending", "events.date ASC"],
                ["Date - Descending", "events.date DESC"],
                ["Event - Ascending", "events.name ASC"],
                ["Event - Descending", "events.name DESC"],
                ["City - Ascending", "locations.name ASC"],
                ["City - Descending", "locations.name DESC"],
                ["Venue - Ascending", "venues.name ASC"],
                ["Venue - Descending", "venues.name DESC"]], params[:order_by]) %>
                <%= hidden_field_tag :name, params[:name] %>
                <%= hidden_field_tag :main_category, params[:main_category] %>
                <%= hidden_field_tag :state, params[:state] %>
                <%= hidden_field_tag :date, params[:date] %>
                <%= hidden_field_tag :page, params[:page] %>
                <%= submit_tag "submit" , name: nil, id: 'sort' %>
            </p>
            <% end %>
          </section>
          <section class="box4 css3">
            <table class="table1">
              <thead>
                <tr>
                  <th>Event</th>
                  <th>Venue</th>
                  <th>City</th>
                  <th>Date</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody>
                <% @events.each_with_index do |event, i| %>
                  <tr <%= 'class=alt' if i % 2 == 0 %> >
                    <td class="event">
                      <%= link_to event.name, collectible_link(event) %>
                    </td>
                    <td class="venue">
                      <%= link_to event.venue.name, collectible_link(event.venue) if event.venue %>
                    </td>
                    <td class="city"><%= link_to event.location.name, collectible_link(event.location) %></a></td>
                    <td class="date">
                      <%= event.long_date %>
                    </td>
                    <td>
                      <%= link_to "Buy", collectible_link(event), class: "btn  button1 css3" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
              <div class="pagination pagination-centered">
          <%= paginate @events %>
              </div>
          </section>
        </section>
        <% else %>
          <section> No results were found. </section>
        <% end %>
      </section>
    </div>
  </div>

app/views/search/index_page.html.erb
  <div class="container">
    <div class="row">
      <section class="span3">
        <%= render 'widgets/filter' %>
      </section>
      <section class="span9">
        <!-- Breadcrumbs -->
        <div id="breadcrumbs" class="row">
          <section class="span12"> <%= link_to "Home", root_path %> <span>Search Results</span> </section>
        </div>
        <!-- /Breadcrumbs -->
        <% if @events.length > 0 %>
        <section class="search-results">
          <section class="sort-by">
            <%= form_tag filter_path, method: 'get', id:"sort-field" do %>
            <p>
              <%= label_tag :order_by, "Sort by" %>
              <%= select_tag :order_by, options_for_select([
                ["Date - Ascending", "events.date ASC"],
                ["Date - Descending", "events.date DESC"],
                ["Event - Ascending", "events.name ASC"],
                ["Event - Descending", "events.name DESC"],
                ["City - Ascending", "locations.name ASC"],
                ["City - Descending", "locations.name DESC"],
                ["Venue - Ascending", "venues.name ASC"],
                ["Venue - Descending", "venues.name DESC"]], params[:order_by]), include_blank: true %>
                <%= hidden_field_tag :name, params[:name] %>
                <%= hidden_field_tag :main_category, params[:main_category] %>
                <%= hidden_field_tag :city, params[:city] %>
                <%= hidden_field_tag :date, params[:date] %>
                <%= hidden_field_tag :page, params[:page] %>
                <%= submit_tag "submit" , name: nil, id: 'sort' %>
            </p>
            <% end %>
          </section>
          <section class="box4 css3">
            <table class="table1">
              <thead>
                <tr>
                  <th>Event</th>
                  <th>Venue</th>
                  <th>City</th>
                  <th>Date</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody>
                <% @events.each_with_index do |event, i| %>
                  <tr <%= 'class=alt' if i % 2 == 0 %> >
                    <td class="event">
                      <%= link_to event.name, collectible_link(event) %>
                    </td>
                    <td class="venue">
                      <%= link_to event.venue.name, collectible_link(event.venue) if event.venue %>
                    </td>
                    <td class="city"><%= link_to event.location.name, collectible_link(event.location) %></a></td>
                    <td class="date">
                      <%= event.long_date %>
                    </td>
                    <td>
                      <%= link_to "Buy", collectible_link(event), class: "btn  button1 css3" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
              <div class="pagination pagination-centered">
          <%= paginate @events %>
              </div>
          </section>
        </section>
        <% else %>
          <section> No results were found. </section>
        <% end %>
      </section>
    </div>
  </div>

app/views/search/show.html.erb
  <div class="container">
    <div class="row">
      <section class="span3">
        <%= render 'widgets/filter' %>
      </section>
      <section class="span9">
        <!-- Breadcrumbs -->
        <div id="breadcrumbs" class="row">
          <section class="span12"> <%= link_to "Home", "/" %> <span>Search Results for “<%= @search_term %>”</span> </section>
        </div>
        <!-- /Breadcrumbs -->
        <% if @events.length > 0 %>
        <section class="search-results">
          <section class="sort-by">
            <%= form_tag free_search_path, method: 'get', id:"sort-field" do %>
            <p>
              <%= label_tag :order_by, "Sort by" %>
              <%= select_tag :order_by, options_for_select([
              	["Date - Ascending", "date ASC"],
              	["Date - Descending", "date DESC"],
              	["Event - Ascending", "name ASC"],
              	["Event - Descending", "name DESC"],
              	["City - Ascending", "locations.name ASC"],
              	["City - Descending", "locations.name DESC"],
              	["Venue - Ascending", "venues.name ASC"],
              	["Venue - Descending", "venues.name DESC"]], params[:order_by]) %>
              	<%= hidden_field_tag :search_term, params[:search_term] %>
              	<%= hidden_field_tag :page, params[:page] %>
              	<%= submit_tag "submit" , name: nil, id: 'sort' %>
            </p>
            <% end %>
          </section>
          <section class="box4 css3">
            <table class="table1">
              <thead>
                <tr>
                  <th>Event</th>
                  <th>Venue</th>
                  <th>City</th>
                  <th>Date</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody>
              	<% i=0 %>
              	<% @events.each do |event| %>
	                <tr <%= 'class=alt' if i % 2 == 0 %> >
	                  <td class="event">
	                  	<%= link_to event.name, collectible_link(event) %>
	                  </td>
	                  <td class="venue">
	                  	<%= link_to event.venue.name, collectible_link(event.venue) if event.venue %>
	                  </td>
	                  <td class="city"><%=link_to event.location.name, collectible_link(event.location) %></td>
	                  <td class="date">
	                  	<%= event.long_date %>
	                  </td>
	                  <td>
	                  	<%= link_to "Buy", collectible_link(event), class: "btn  button1 css3" %>
	                  </td>
	                </tr>
	                <% i = i + 1 %>
	                <% end %>
              </tbody>
            </table>
	            <div class="pagination pagination-centered">
					<%= paginate @events %>
	            </div>
          </section>
        </section>
        <% else %>
        	<section> No results were found. </section>
        <% end %>
      </section>
    </div>
  </div>