config/routes.rb
AllSeats::Application.routes.draw do

  get "/collections/:id" => "collections#show", as: :collection

  mount Rich::Engine => '/rich', :as => 'rich'

  get "search/events" => 'search#index', as: :filter
  get "search/free_search" =>'search#show', as: :free_search
  get "search/autocomplete", :to => 'search#autocomplete', :as => :autocomplete

  get "/performer/events" => 'performers#events', as: :performer_tickets

  get "/venue/events" => 'venues#events', as: :venue_tickets

  get 'static/:permalink', :controller => 'static_pages', :action => 'show', :as => :static_page

  resources :performers, :only => [:show]
  resources :events, :only => [:show]
  resources :venues, :only => [:show]
  resources :locations, :only => [:show, :index]
  resources :contact_us_messages, :only => [:create]

  get "home/home"
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to=>'home#home'

  get "/:id" => "categories#show", as: :category
  get "/:category_id/:id" => "performers#show", as: :long_performer
  get "/:category_id/:performer_id/:date" => "events#show", as: :long_event

  post '/contact_us_messages/new'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  ancestry       :string(255)
#  tnid           :integer
#  ancestry_depth :integer          default(0)
#  slug           :string(255)
#

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  include SeoAble


  attr_accessible :slug, :name, :parent_id, :collection_ids, :event_ids, :performer_ids, :meta_title,
    :meta_description, :h1, :description, :visible, :active, :image_path, :owned_collections_ids, :as => [:default, :admin]
  has_many :listings, :as => :collectible
  has_many :collections, :through => :listings
  has_many :owned_collections, class_name: 'Collection', foreign_key: 'category_id'

  has_many :performers
  has_many :events
  has_ancestry :cache_depth => true

  validates :name, :presence => true

  liquid_methods :name

  scope :visible, where(visible: true)
  scope :active, where(active: true)
  scope :feaured, where(feaured: true)
  scope :popular, order("clicks")


  def image_url
    if self.image_path and ! self.image_path.empty?
      self.image_path
    else
      "no-image.png"
    end
  end

  def grandparent
    if self.parent
      self.parent.parent
    else
      nil
    end
  end

  # ==== Unused ====
  # def all_performers
  #   Performer.active.where(category_id: self.subtree_ids)
  # end

  # ==== Unused ====
  # def all_events
  #   Event.future.active.where(category_id: self.subtree_ids)
  # end

  # ==== Unused =====
  # def all_events_alphabetical_hash
  #   Event.alphabetical_hash(self.all_events)
  # end

  def get_featured(array)
    featured = nil
    featured_array = array.find_all {|item| item.featured}
    if featured_array.empty?
      (array.sort_by {|item| item.clicks}).last
    else
      featured_array.sample
    end
  end

  def should_generate_new_friendly_id?
    new_record?
  end

  # Collects all visible children of this category and visible children of all non-visible children of this category.
  def visible_children
    arr = []
    self.children.each do |child|
      if child.visible && child.active
        arr << child
      else
        arr = arr + child.visible_children if child.active
      end
    end
    arr
  end

  # Collectes the performers of this category (if it is visible) and each visible child.
  def visible_performers
    arr = self.performers.select {|performer| performer.active}
    if self.visible
      self.children.each {|child|   arr = arr + child.visible_performers if !child.visible && child.active}
    else
      self.children.each {|child| arr = arr + child.visible_performers if child.active}
    end
    arr
  end

  def self.flatten
    self.all.each do |category|
      if category.name == "-"
        parent = category.parent
        category.performers.each do |performer|
          performer.category = parent
          performer.save
        end
        category.events.each do |event|
          event.category = parent
          event.save
        end
        category.destroy
      end
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.visible.active.find(params[:id])

    set_seo_vars(@category)

    @sub_categories = @category.visible_children

    @performers = @category.visible_performers

    @collections = @category.owned_collections

    if session[:city]
      city = Location.find_by_display_name session[:city]
      @local_events = Event.future.active.where(location_id: city.id, category_id: @category.id).popular if city
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
	
end

app/views/categories/_breadcrumbs.html.haml
#breadcrumbs.row
  .span6
    = link_to(category.grandparent.name, collectible_link(category.grandparent)) if category.grandparent && category.grandparent.visible && category.grandparent.active
    = link_to(category.parent.name, collectible_link(category.parent)) if category.parent && category.parent.visible && category.parent.active
    %span= category.nil? ? params[:id] : category.name

app/views/categories/_featured.html.erb
<article class="box3 post featured2 css3 clearfix" id="featured">
     <h2>Featured <%= @category.name %></h2>
     <%= image_tag @featured.image_url ,alt: @featured.name,  class: "alignright" %>
     <section class="entry">
     <%= markdown @featured.description if @featured.description %>
      </section>
     <p class="read-more"><a href="#" class="show">Read more...</a> <a href="#" class="hide">Read less...</a></p>
     <section class="post-footer">
     <a href='<%= collectible_link(@featured) %>'
     <button class="btn  button1 css3">Buy <%= @featured.name %> Tickets Now</button>
     </a>
     </section>
</article>

app/views/categories/_popular.html.erb
<% unless @popular.empty? %>
  <section class="box3 css3 popular-broadway-tickets">
    <h2>Popular <%= @category.nil? ? params[:id] : @category.name %> Tickets</h2>
    <ul class="thumbnails list4">
      <% i=1 %>
      <% @popular.each do |event| %>
      <li <%= 'class=outermost' if i == 4 %> <%= 'class=last' if i == 8 %>>
        <div class="thumbnail"> <a href="<%= collectible_link(event) %>"><%=image_tag event.image_url, alt: event.name %></a>
          <h3><%= link_to event.name.truncate(35), collectible_link(event) %></h3>
          <a href="<%= collectible_link event %>">
          <button class="btn  button1 css3">Tickets</button>
          </a>
        </div>
      </li>
      <% i = i + 1 %>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/categories/show.html.haml
#content.clearfix
    .container
        .row
            = @left_sidebar
            %section.span6
                = render 'breadcrumbs', category: @category
                %article.post.about
                    %h1.nice-title= @page_h1
                    = image_tag @category.image_path unless @category.image_path.nil? || @category.image_path.empty?
                -if @local_events && !@local_events.empty?
                    =render "shared/local_events", events: @local_events
                -if @featured
                    = render '/categories/featured'
                / /Featured
                - if @category.description
                    %article.post.about
                        = markdown(@category.description)
                - if @performers.empty? && @sub_categories.empty? & @collections.empty?
                    %section.box4.css3
                        %table.table1
                            %thead
                                %tr
                                    %th There are no items in this category.
                            %tbody
                - else
                    - unless @collections.empty?
                        %section.box4.css3
                            %table.table1
                                %thead
                                    %tr
                                        %th{'colspan' => 2} Collections in this category:
                                       
                                %tbody
                                    - @collections.each_with_index do |item,i|
                                        - alt_class = ""
                                        - alt_class = "alt" if (i % 4 == 0)
                                        - if (i % 2 == 0)
                                            %tr{:class => alt_class}
                                                %td
                                                    = link_to item.name, collection_path(item)
                                                -if (i+1 < @collections.length)
                                                    %td
                                                        = link_to @collections[i+1].name, collection_path(@collections[i+1])
                                                -else
                                                    %td

                    - unless @performers.empty?
                        %section.box4.css3
                            %table.table1
                                %thead
                                    %tr
                                        %th Performers in this category:
                                        %th
                                %tbody
                                    - @performers.each_with_index do |item,i|
                                        - alt_class = ""
                                        - alt_class = "alt" if (i % 4 == 0)
                                        - if (i % 2 == 0)
                                            %tr{:class => alt_class}
                                                %td
                                                    = link_to @performers[i].name, collectible_link(@performers[i])
                                                -if (i+1 < @performers.length)
                                                    %td
                                                        = link_to @performers[i+1].name, collectible_link(@performers[i+1])
                                                -else
                                                    %td
                                                            
                                    
                    - unless @sub_categories.empty?
                        %section.box4.css3
                            %table.table1
                                %thead
                                    %tr
                                        %th{'colspan' => 2} Sub-categories in this category:
                                       
                                %tbody
                                    - @sub_categories.each_with_index do |item,i|
                                        - alt_class = ""
                                        - alt_class = "alt" if (i % 4 == 0)
                                        - if (i % 2 == 0)
                                            %tr{:class => alt_class}
                                                %td
                                                    = link_to @sub_categories[i].name, collectible_link(@sub_categories[i])
                                                -if (i+1 < @sub_categories.length)
                                                    %td
                                                        = link_to @sub_categories[i+1].name, collectible_link(@sub_categories[i+1])
                                                -else
                                                    %td
                                    
                %article.post
                    %h4 Miscellaneous Information:
                    %p AnyTickets.com is a licensed ticket broker and AnyTickets.com supplies the highest quality #{@category.name} tickets at the best price on the internet. AnyTickets.com is 100% determined on providing customers with unsurpassed customer service and the highest quality #{@category.name} tickets available.
                    %h4 Shipping:
                    %p When you find #{@category.name} tickets that you would like to purchase,they can be purchased online via our encrypted safe and secure server.Or if you prefer,you may order by phone.for faster service, please order online.your #{@category.name} order will be fulfilled within 6-24 hours.All tickets will be sent via federal express.The shipping address must be the same as your billing address at which you receive your credit card statement.If this is not the case, we will need to obtain a fax written authorization from you.If you would like to do this, you should contact one of our ticket representatives.
                    %h4 Availability:
                    %p The ticket inventory is updated on a hourly basis.However,if the tickets you wish to purchase are no longer available, we will contact you immediately and you will be given other options or you may choose an alternative set of tickets that we wil try to offer similar to the price range of your original order.
            = @right_sidebar