config/routes.rb
AllSeats::Application.routes.draw do

  get "/collections/:id" => "collections#show", as: :collection

  mount Rich::Engine => '/rich', :as => 'rich'

  get "search/events" => 'search#index', as: :filter
  get "search/free_search" =>'search#show', as: :free_search
  get "search/autocomplete", :to => 'search#autocomplete', :as => :autocomplete

  get "/performer/events" => 'performers#events', as: :performer_tickets

  get "/venue/events" => 'venues#events', as: :venue_tickets

  get 'static/:permalink', :controller => 'static_pages', :action => 'show', :as => :static_page

  resources :performers, :only => [:show]
  resources :events, :only => [:show]
  resources :venues, :only => [:show]
  resources :locations, :only => [:show, :index]
  resources :contact_us_messages, :only => [:create]

  get "home/home"
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to=>'home#home'

  get "/:id" => "categories#show", as: :category
  get "/:category_id/:id" => "performers#show", as: :long_performer
  get "/:category_id/:performer_id/:date" => "events#show", as: :long_event

  post '/contact_us_messages/new'

end

app/controllers/application_controller.rb
require "controller_view_shared_methods"
class ApplicationController < ActionController::Base
  include ControllerViewSharedMethods

  protect_from_forgery

  before_filter :reload_rails_admin, if: :rails_admin_path?
  before_filter :set_variables

  def not_found
    raise ActiveRecord::RecordNotFound, "Page not found"
  end


  def liquify(template, opts={})
    begin
      tmpl = Liquid::Template.parse(template)
      tmpl.render(opts, registers: {controller: self}).html_safe
    rescue => msg
     logger.warn msg
     msg
    end
  end

  def liquid_description(description, liquid_opts={})
    	paragraphs = description.split(/\n\n|\r\n\r\n|\n\r\n\r/).compact
    	header = paragraphs.shift

    	render(partial: 'widgets/description', locals: {
      		paragraphs: paragraphs,
      		header: header,
      		liquid_opts: liquid_opts
    	})
  end

  def set_variables
    #loads footer and navbar links

    @left_sidebar = liquify Section.find_by_name('home left sidebar').content
    @right_sidebar = liquify Section.find_by_name('home right sidebar').content

    @footer = liquify Section.find_by_name('footer').content

    #find the collections for the navbar dropdown as stored in the navbar links section
    header_collection_names = Section.find_by_name('navbar links')

    if header_collection_names
      array = []
      header_collection_names.content.split(',').map(&:strip).each do |name|
        collection = Collection.find_by_name name
        array << collection if collection
      end
      @header_collections =  array
    else
      @header_collections = []
    end
    if params[:city] == ""
      session[:city] = nil
      session[:dont_check_city] = true
    else
      if params[:city] && params[:city] != ""
        session[:city] = params[:city]
      end
      unless session[:dont_check_city]
        begin
          if session[:city].nil? || session[:city] == ""
            location = GeoLocation.find request.remote_ip
            if location[:city] && location[:city] != "" && location[:city] != "(Private Address)"
              city_name = location[:city].strip.downcase.split(' ').map {|word| word.capitalize}.join(' ')
              city = Location.find_by_display_name(city_name) || Location.find_by_name(city_name)
              session[:city] =  city.try(:display_name) || city_name
            end
          end
        rescue Exception => e
          session[:city] = params[:city] if params[:city] && params[:city] != ""
        end
      end
    end
  end

  def set_seo_vars(model)
    @page_h1          = model.h1_text
    set_meta_tags :title => model.meta_title_text,
                  :description => model.meta_description_text
  end


  private

  def reload_rails_admin
    models = %W(Category, Collection, Venue, Section)
    models.each do |m|
      RailsAdmin::Config.reset_model(m)
    end
    RailsAdmin::Config::Actions.reset

    load("#{Rails.root}/config/initializers/rails_admin.rb")
  end

  def rails_admin_path?
    controller_path =~ /admin/ && Rails.env == "development"
  end
end

app/helpers/application_helper.rb
require "controller_view_shared_methods"
module ApplicationHelper
  include ControllerViewSharedMethods


  def markdown(text)
  	markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :hard_wrap => true, :autolink => true)
  	markdown.render(text).html_safe
  end

  def get_location_path city_name
    city = Location.find_by_name city_name || not_found
    location_path city
  end

  
  

  #You will need to replace everything in angle brackets (<,>) above with the appropriate values. “<bid>” is your broker ID (given above), “<sid>” is your site number (also given above), “<tgid>” is the ID of the ticket group, “<evtid>” is the event ID of all the ticket groups on the page, “<price>” is the price you have quoted on your page (note that this value is passed for logging purposes only), and “<treq>” is the number of tickets requested by the customer.
  #“<sessionid>” must be a unique, 5-character alphanumeric random string (e.g., “gs32X”) for every checkout link on the page. Again, each session ID must be unique. Here is sample JavaScript code for generating session IDs client-side:
  def checkout_url(event_id, ticket_group_id, price, amount)
    broker_id = 932
    site_number = 20
    session_id = random_session
    "https://tickettransaction2.com/Checkout.aspx?brokerid=#{broker_id}&sitenumber=#{site_number}&tgid=#{ticket_group_id}&evtid=#{event_id}&price=#{price}&treq=#{amount}&SessionId=#{session_id}"
  end

def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end

  def random_session
    charset = %w{ 1 2 3 4 5 6 7 8 9 a b c d e f g h j k m n p q r x y z A C D E F G H J K M N P Q R T V W X Y Z}
    (0...5).map{ charset.to_a[rand(charset.size)] }.join
  end

  def google_analytics(id = nil)
    content_tag(:script, :type => 'text/javascript') do
      "var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{id}']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })()".html_safe
    end if !id.blank? && Rails.env.production?
  end

end

app/views/application/_flash_notice.html.erb
<% if flash[:notice] %>
	<div class="row">
		<section class="span12" >
			<section class="alert alert-warning css3">
				<a class="close" href='#' data-dismiss='alert'></a>
				<strong>
					Notice:
				</strong>
				<%= flash[:notice] %>
			</section>
		</section>
	</div>
<% end %>

app/views/application/_header.html.erb
<header id="header" class="clearfix">
  <div class="container">
    <div class="row">
      <section class="logo span3">
        <a href="/" rel="home" title="Go to homepage"><span>Any Tickets</span></a>
      </section>
      <section class="span9">
        <!-- Global Navigation-->
        <nav id="global-navigation" class="navbar">
          <ul class="nav">
            <li><a href="<%=static_page_path(permalink: "about_us") %>">About Us</a></li>
          </ul>
        </nav>
        <!--/ Global Navigation-->
        <!-- Search Form -->
        <section id="search-form" class="span6">
          <%=  form_tag free_search_path, method: 'get', class: 'form-search' do %>
            <%= text_field_tag :search_term, params[:search_term], id: "searchinput", autocomplete: "off", class: "input-medium search-query", placeholder: "Search by artist, performer, team, or category" , data: {provide: "typeahead",source: ""}%>
            <%= submit_tag "", name: nil, class: "btn" %>
          <% end %>
        </section>
        <!-- /Search Form -->
      </section>
    </div>
    <div class="row">
      <div class="span12">
        <!-- Main Navigation-->
        <nav id="main-navigation" class="navbar css3">
          <ul class="nav clearfix">
            <li class="active first"><a href="/">Home</a></li>

            <% @header_collections.each do |collection| %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= collection.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                  <% collection.items.each do |item| %>
                   <li class="wide-li"> <%= link_to item.name, collectible_link(item) %> </li>
                  <% end %>
                </ul>
              </li>
            <%end%>
            <!-- <li class="last atlanta dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Cities<b class="caret"></b></a>
              <ul class="dropdown-menu" id="last-dropdown" role="menu" aria-labelledby="dropdownMenu">
                <li><a tabindex="-1" href="#">Type city name</a></li>
                <input type="text" id="city-search" data-provide="typeahead" data-items="4" data-source='<%=Location.cities_list.to_s%>'>
              </ul>
            </li> --> 
            <li class="last atlanta dropdown">
              <%= form_tag root_path, method: 'get', id:"location_select" do %>
                <%= select_tag :city, options_for_select(Location.cities_list, session[:city]), id: "e2", include_blank: true %>
                <%= submit_tag %>
              <% end %>
            </li>
          </ul>
        </nav>
        <!--/ Main Navigation-->
      </div>
    </div>
  </div>
</header>

app/views/application/_old_dropdown.html.erb
<div class="pulldown-menu">
  <div class="pulldown-header-container">
    <div class="pulldown-text">
      <%= collection.name %>
    </div>
  </div>
  <% slice_size = if collection.items.size % 3 ==0
      collection.items.size / 3
    else
      (collection.items.size / 3) + 1
      end %>
  <% columns = collection.items.each_slice(slice_size).to_a %>
  <div style="width: 114px;" class="pulldown-items-container">
    <div class="tags-panel pulldown-items">
      <div class="tags-list">
        <div class="column col-1">
          <% columns[0].each do |item| %>
            <div style="min-width: 114px;" class="pulldown-item">
              <%= link_to item.name, collectible_link(item), class: 'tag-item' %>
            </div>
          <% end %>
        </div>
        <div class="column col-2">
          <% columns[1].each do |item| %>
            <div style="min-width: 114px;" class="pulldown-item">
              <%= link_to item.name, collectible_link(item), class: 'tag-item' %>
            </div>
          <% end %>
        </div>
        <div class="column col-3">
          <% columns[2].each do |item| %>
            <div style="min-width: 114px;" class="pulldown-item">
              <%= link_to item.name, collectible_link(item), class: 'tag-item' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>